name: Sync with upstream

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git remote add upstream git@github.com:chatwoot/chatwoot.git
      - name: Pull and merge upstream changes
        run: |
          git fetch upstream
          git checkout develop
          git merge upstream/master
          git push origin develop

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Sync with upstream
          title: Sync with upstream
          body: Automated sync with upstream repository
          base: main
          branch: sync-upstream
