slack:
  id: slack
  name: Slack
  logo: slack.png
  description: "'Be less busy' -  Slack is the chat tool that brings all your communication together in one place. By integrating Slack with Chatwoot, you can get notified of all the new conversations in chatwoot right inside your Slack."
  action: https://slack.com/oauth/v2/authorize?scope=incoming-webhook,commands,chat:write,users:read,users:read.email
  