version: "2"
plugins:
  rubocop:
    enabled: true
    channel: rubocop-0-73
  eslint:
    enabled: false
    exclude_patterns:
      - "tests/"
      - "spec/"
      - "specs/"
  csslint:
    enabled: true
  scss-lint:
    enabled: true
  brakeman:
    enabled: true
