version: '3'

services:
  base: &base
    build:
      context: .
      dockerfile: ./docker/development.Dockerfile
    tty: true
    stdin_open: true
    image: chatwoot:development

  rails:
    <<: *base
    build:
      context: .
      dockerfile: ./docker/dockerfiles/Dockerfile.rails
    image: chatwoot-rails:development
    volumes:
      - ./:/app:delegated
      - node_modules_rails:/app/node_modules # Node modules shared across containers
      - packs:/app/public/packs:delegated
    depends_on:
      - postgres
      - redis
    links:
      - webpack
    ports:
      - 3000:3000
    env_file: .env.development
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpack
      - NODE_ENV=development
      - RAILS_ENV=development
    entrypoint: docker/entrypoints/rails.sh
    command: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]
  
  webpack:
    <<: *base
    build:
      context: .
      dockerfile: ./docker/dockerfiles/Dockerfile.webpack
    image: chatwoot-webpack:development
    volumes:
      - ./:/app:delegated
      - node_modules_webpack:/app/node_modules # Node modules shared across containers
      - packs:/app/public/packs:delegated
    ports:
      - 3035 # Webpack dev server
    env_file: .env.development
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
      - NODE_ENV=development
      - RAILS_ENV=development
    entrypoint: docker/entrypoints/webpack.sh
    command: bin/webpack-dev-server

  postgres:
    image: postgres:9.6
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres:/data/postgres
    environment:
      - POSTGRES_DB=chatwoot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis:/data/redis
    ports:
      - '6379:6379'

volumes:
  postgres:
  redis:
  bundle:
  packs:
  node_modules_rails:
  node_modules_webpack: