version: '3'

services:
  base: &base
    build:
      context: .
      dockerfile: ./docker/test.Dockerfile
    tty: true
    stdin_open: true
    image: chatwoot:test

  rspec:
    <<: *base
    build:
      context: .
      dockerfile: ./docker/dockerfiles/rspec.Dockerfile
    image: chatwoot-rails:test
    volumes:
      - ./:/app:delegated
      - node_modules:/app/node_modules # Node modules shared across containers
      - packs:/app/public/packs:delegated
    depends_on:
      - postgres
      - redis
    ports:
      - 3000:3000
    env_file: .env.example
    environment:
      - NODE_ENV=test
      - RAILS_ENV=test
    entrypoint: docker/entrypoints/rspec.sh
    command: ["bundle", "exec", "rspec"]


  postgres:
    image: postgres:9.6
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres:/data/postgres
    environment:
      - POSTGRES_DB=chatwoot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis:/data/redis
    ports:
      - '6379:6379'

volumes:
  postgres:
  redis:
  bundle:
  packs:
  node_modules: