type: object
properties:
  id:
    type: string
    description: The id of the integeration
  name:
    type: string
    description: The name of the integeration
  description:
    type: string
    description: The description about the team
  hook_type:
    type: string
    description: Whether the it's account or inbox integeration
  enabled:
    type: boolean
    description: Whether the integration is enabled for the account
  allow_multiple_hooks:
    type: boolean
    description: Whether multiple hooks can be created for the integration
  hooks:
    type: array
    description: If there are any hooks created for this integeration
