# https://github.com/ondrejbartas/sidekiq-cron
# use https://crontab.guru/ to validate
# validations for this file exist in /spec/configs/schedule_spec.rb

# executed At 12:00 on every day-of-month.
internal_check_new_versions_job:
  cron: '0 12 */1 * *'
  class: 'Internal::CheckNewVersionsJob'
  queue: scheduled_jobs

# executed At every 5th minute..
trigger_scheduled_items_job:
  cron: '*/5 * * * *'
  class: 'TriggerScheduledItemsJob'
  queue: scheduled_jobs

# executed At every 5th minute..
trigger_imap_email_inboxes_job:
  cron: '*/1 * * * *'
  class: 'Inboxes::FetchImapEmailInboxesJob'
  queue: scheduled_jobs


# execute At every 12 hours to validate the instagram story link
trigger_instagram_mock_webhook_job:
  cron: '* 6 * * *'
  class: 'Webhooks::FetchInstagramMessagesJob'
  queue: scheduled_jobs
