# #
# # This action will strip the enterprise folder
# # and run the spec.
# # This is set to run against every PR.
# #

name: Run Nightly installer
on:
  push:
    branches:
      - develop
      - master
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:

    - name: ls
      run: |
        ls
        pwd

    - name: get installer
      run: |
        wget https://get.chatwoot.app/linux/install.sh
        chmod +x install.sh
        whoami
        ls -ltra

    - name: create input file
      run: |
        echo "no" > input
        echo "yes" >> input

    - name: Run the installer
      run: |
        sudo ./install.sh --install < input

    # temp fix for postgresql not starting 
    # automatically
    - name: start postgresql service
      if: always()
      run: |
        sudo service postgresql start

    #re-running the installer again
    - name: Run the installer 2
      if: always()
      run: |
        sudo ./install.sh --install < input

        #   - name: logs
        #      if: always()
        #      run: tail -100 /var/log/chatwoot-setup.log

    - name: Verify
      if: always()
      run: |
        curl http://localhost:3000/api

    - name: Setup tmate session
      if: always()
      uses: mxschmitt/action-tmate@v3


