# #
# # This action will publish Chatwoot CE docker image.
# # This is set to run against merges to develop, master
# # when tags are created.
# #

name: Publish Chatwoot CE docker images
on:
  push:
    branches:
      - develop
      - master
    tags:
      - v*
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Strip enterprise code
        run: |
          rm -rf enterprise
          rm -rf spec/enterprise

      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'

      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ github.ref_name }}'

         #      -
         # name: Build and push
         #uses: docker/build-push-action@v2
         #with:
         # file: docker/Dockerfile
         # push: false
         # tags: chatwoot/chatwoot:latest-ce

