# #
# # This action will strip the enterprise folder
# # and run the spec.
# # This is set to run against every PR.
# #

name: Run Chatwoot CE spec
on:
  push:
    branches:
      - develop
      - master
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        # tmpfs makes DB faster by using RAM
        options: >-
          --mount type=tmpfs,destination=/var/lib/postgresql/data
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.2 # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Strip enterprise code
      run: |
        rm -rf enterprise
        rm -rf spec/enterprise

    - name: Create database
      run: bundle exec rake db:create

    - name: Seed database
      run: bundle exec rake db:schema:load

    # Run rails tests
    - name: Run backend tests
      run: |
          bundle exec rspec ./spec/controllers/dashboard_controller_spec.rb
          bundle exec rspec ./spec/controllers/installation/onboarding_controller_spec.rb
          bundle exec rspec ./spec/controllers/service/responses_controller_spec.rb
          bundle exec rspec ./spec/controllers/super_admin/installation_configs_controller_spec.rb
          bundle exec rspec ./spec/controllers/widgets_controller_spec.rb
