# #
# # This action will strip the enterprise folder
# # and run the spec.
# # This is set to run against every PR.
# #

name: Run Chatwoot CE spec
on:
  push:
    branches:
      - develop
      - master
  pull_request:
  workflow_dispatch:
jobs:
  action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1 # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    # - run: bundle exec rake
    - name: Strip enterprise code
      run: |
        rm -rf enterprise
        rm -rf spec/enterprise
